default_ingredient_list = ['lentils', 'kale', 'shallots', 'swiss cheese', 'anchovies', 'Quiche', 'cashew nut',
                           'Waffles', 'chicken liver', 'parsley', 'babaganoosh', 'Toast', 'bouillon', 'hamburger',
                           'hoisin sauce', 'chaurice sausage', 'fennel', 'curry', 'clams', 'spaghetti squash',
                           'haiku roll', 'ancho chili peppers', 'flax seed', 'remoulade', 'alfredo sauce', 'avacado',
                           'broccoli', 'moo shu wrappers', 'truffles', 'carne asada', 'Pancakes', 'tomato puree',
                           'steak', 'Guancamole', 'crab', 'bison', 'almond', 'snap peas', 'corn', 'basil', 'barley',
                           'grouper', 'romaine lettuce', 'tarragon', 'Spaghetti', 'edimame', 'Tater tots', 'jambalaya',
                           'amaretto', 'bean sauce', 'lobster', 'granola', 'sour cream', 'yogurt', 'cilantro',
                           'avocados', 'duck', 'dates', 'kumquats', 'spearmint', 'celery seeds', 'cider vinegar',
                           'sardines', 'bacon', 'jack cheese', 'haddock', 'shitakes', 'franks', 'pickles', 'ginger',
                           'ginger ale', 'french fries', 'Irish stew', 'breadfruit', 'dips', 'bass',
                           'potato chips', 'lemons', 'salmon', 'Wine', 'caviar', 'apple butter', 'bard', 'coconut oil',
                           'Cabbage', 'carrots', 'asparagus', 'kiwi', 'chocolate', 'unsweetened chocolate',
                           'tomato sauce', 'oatmeal', 'gumbo', 'panko bread crumbs', 'pancetta', 'Reuben',
                           'condensed milk', 'Pizza', 'curry paste', 'rosemary', 'ketchup', 'cornmeal', 'turkeys',
                           'rice', 'split peas', 'pink beans', 'maraschino cherries', 'dried leeks', 'bruschetta',
                           'molasses', 'spinach', 'cucumbers', 'cupcakes', 'mesclun greens', 'bagels', 'apples',
                           'Bruscetta', 'ice cream', 'asiago cheese', 'tomatoes', 'pistachios', 'eggs', 'vegemite',
                           'corn syrup', 'cake', 'hash browns', 'sazon', 'veal', 'habanero chilies', 'red chili powder',
                           'Tabasco sauce', 'fajita', 'portabella mushrooms', 'Goji berry', 'brazil nuts', 'parsnips',
                           'enchilada', 'Quesadilla', 'hummus', 'chimichangadates', 'sherry', 'bok choy', 'horseradish',
                           'rhubarb', 'quail', 'mint', 'Irish cream liqueur', 'Pepperoni', 'melons', 'pears',
                           'cocoa powder', 'bluefish', 'Mandarin oranges', 'cooking wine', 'tartar sauce', 'papayas',
                           'honey', 'shrimp', 'black olives', 'canola oil', 'cheddar cheese', 'alfalfa', 'cider',
                           'corn flour', 'feta cheese', 'fondu', 'onions', 'water', 'sauerkraut', 'cornstarch',
                           'bourbon', 'cabbage', 'brown rice', 'baguette', 'balsamic vinegar', 'ahi tuna ', 'mushrooms',
                           'pasta', 'chips', 'garlic', 'chicory', 'allspice', 'maple syrup', 'chickpeas', 'chard',
                           'hot dogs', 'baking soda', 'arugala', 'sausages', 'sweet peppers', 'five-spice powder',
                           'thyme', 'chili powder', 'Havarti cheese', 'artichokes', 'beef', 'fish  ', 'tuna',
                           'eel sushi', 'sweet potatoes', 'donuts', 'sunflower seeds', 'coconuts', 'salsa', 'celery',
                           'prunes', 'crayfish', 'hamburger ', 'beer', 'jicama', 'rum', 'rice vinegar', 'bean threads',
                           'hazelnuts', 'kidney beans', 'halibut', 'grapes', 'chambord', 'adobo', 'chipotle peppers',
                           'capers', 'Ziti', 'cherries', 'hot sauce', 'eel', 'pico de gallo', 'green onions',
                           'sesame seeds', 'Zucchini', 'French toast', 'chai', 'focaccia', 'guavas', 'raspberries',
                           'huckleberries', 'zinfandel wine', 'croutons', 'mayonnaise', 'barbecue sauce', 'cumin',
                           'pea beans', 'tonic water', 'tortillas', 'squash', 'gorgonzola', 'squid', 'Graham crackers',
                           'brussels sprouts', 'coriander', 'summer squash', 'rose water', 'mustard seeds', 'borscht',
                           'gelatin', 'tofu', 'white beans', 'English muffins', 'jelly', 'cream cheese', 'snapper',
                           'mustard', 'broccoli raab', 'Romano cheese', 'buritto', 'paprika', 'acorn squash  ',
                           'snow peas', 'cannellini beans', 'red snapper', 'ham', 'raisins', 'creme fraiche',
                           'watermelons', 'artificial sweetener', 'BBQ', 'Linguine', 'plantains', 'strawberries',
                           'monkfish', 'powdered sugar', 'Spinach', 'cheese', 'buckwheat', 'potatoes', 'goose', 'beets',
                           'lima beans', 'jelly beans', 'huenos rancheros', 'pumpkins', 'salt', 'blueberries',
                           'navy beans', 'graham crackers', 'custard', 'sushi', 'radishes', 'berries',
                           'red pepper flakes', 'ale', 'okra', 'soy sauce', 'tea', 'aioli', 'date sugar', 'pork',
                           'liver', 'cottage cheese', 'limes', 'orange peels', 'vinegar', 'olives', 'cactus', 'Kahlua',
                           'mackerel', 'apricots', 'green beans', 'Garlic', 'black-eyed peas', 'soybeans',
                           'andouille sausage', 'Marsala', 'jam', 'marshmallows', 'walnuts', 'geese', 'flour', 'coffee',
                           'heavy cream', 'red beans', 'lemon juice', 'poultry seasoning', 'Cappuccino Latte',
                           'red cabbage', 'blue cheese', 'chicken', 'Moose', 'Yogurt', 'baked beans', 'cream', 'figs',
                           'dill', 'swordfish', 'rice wine', 'peanuts', 'cayenne pepper', "pig's feet", 'fish sauce',
                           'barley sugar', 'acorn squash', 'rice paper', 'Lasagna', 'applesauce', 'cauliflower',
                           'kabobs', 'sea cucumbers', 'sugar', 'Ostrich', 'asian noodles ', 'zest', 'cinnamon',
                           'Venison', 'chowder', 'butter', 'almond butter', 'cream of tartar', 'dumpling', 'Milk',
                           'cantaloupes', 'apple pie spice', 'brown sugar', 'cod', 'lemon Peel', 'vermouth',
                           'provolone', 'Worcestershire sauce', 'beans', 'breadcrumbs', 'bay leaves', 'garlic powder',
                           'eggrolls', 'jerky', 'water chestnuts', 'scallops', 'Walnuts', 'almond paste', 'wasabi',
                           'cloves', 'marmalade', 'honeydew melons', 'brunoise', 'bread', 'white chocolate', 'chutney',
                           'chestnuts', 'Meatballs', 'baking powder', 'catfish', 'rabbits', 'olive oil', 'poppy seeds',
                           'margarine', 'pecans', 'nectarines', 'milk', 'eggplants', 'sweet chili sauce', 'bisque',
                           'venison', 'buttermilk', 'mascarpone', 'cereal', 'mozzarella', 'ricotta cheese',
                           'pumpkin seeds', 'half-and-half', 'Italian bread', 'dumplings', 'Noodles', 'pinto beans',
                           'jalapeno', 'plum tomatoes', 'curry powder', 'broth', 'Parmesan cheese', 'grapefruits',
                           'pepper', 'bacon grease', 'lettuce', 'crabs', 'plums', 'blackberries', 'pesto', 'cookies',
                           'succotash', 'soymilk', 'gouda', 'oranges', 'pine nuts', 'bean sprouts', 'artichoke',
                           'won ton skins', 'trout', 'pomegranates', 'French dip', 'cremini mushrooms', 'oregano',
                           'pheasants', 'corned beef', 'gnocchi', 'chili sauce', 'turtle', 'almond extract', 'antelope',
                           'lemon grass', 'Avocado roll', 'almonds', 'falafel', 'peanut butter', 'tomato paste',
                           'pineapples', 'wild rice', 'Milkshake', 'tomato juice', 'wine vinegar', 'alligator',
                           'albacore tuna', 'herring', 'mussels', 'lamb', 'cranberries', 'chives', 'onion powder',
                           'leeks', 'peaches', 'Lamb', 'fennel seeds', 'Indian food', 'Canadian bacon', 'prawns',
                           'coconut milk', 'peas', 'couscous', 'Apple juice', 'bananas', 'brandy', 'lobsters', 'sage',
                           'wine', 'prosciutto', 'chili peppers', 'kingfish', 'raw sugar', 'aquavit', 'Porter',
                           'curry leaves', 'black beans', 'vanilla', 'colby cheese', 'passion fruit', 'octopus',
                           'vanilla bean', 'grits', 'flounder', 'arugula', 'turnips', 'macaroni', 'anchovy paste']
